### PR TITLE
Use original image size for better readability

### PR DESCRIPTION
**Pull request by sternenseemann**

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Cool, can you also adjust the link it points to, please?

**Comment by sternenseemann** [comment]
I have used the magic of force push.

**Comment by Leonidas-from-XIV** [comment]
Your wish has been granted.

**Comment by abbysmal** [comment]
I guess we can merge ?

**Comment by abbysmal** [comment]
Merged, thank you! Finally we got this picture right. :-)

**Comment by Leonidas-from-XIV** [comment]
Oops, forgot to actually press the merge button.

**Pull request merged**
