### PR TITLE
Add a post about canopy's future

### PR DESCRIPTION
**Pull request by abbysmal**
WIP

### CODE REVIEW

**Comment by avsm** [comment]
doesnt seem to have updated live for some reason...

**Comment by abbysmal** [comment]
Looks like the server didn't receive any request from Github… trying to reproduce.

**Comment by abbysmal** [comment]
Something is wrong with either Decompress or Irmin, trying to find out what. Found some bugs already, but need to isolate them. :)

**Comment by abbysmal** [comment]
This is fixed for now, that was some mistake on my side, but that allowed me to find some weird things with Decompress while testing. Thank you for reporting. :)

**Pull request merged**
